# This file was generated by GoReleaser. DO NOT EDIT.
cask "kpg" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kpg"]
    end
  end

  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "2ca080ab4ade62afd261162d5dea1ae918e82aefa7840e90d910d2dd8abf29f1"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5b0848d19e5826a97843b8fb3ce761b3494819b0048009451b5e24b06670e15"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1969c70f3ed7db0420464dd0a31a2c94e945ea7ac33557dfc2294682ca85fc6c"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec6025579bda63a4501ead8c9c209a2e9c60973e055caced65c11b5f5fd51138"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kpg"
  desc "Command-first CLI for connecting to Kubernetes-hosted Postgres databases"
  homepage "https://github.com/pscheid92/kpg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kpg"

  generate_completions_from_executable "kpg",
    shell_parameter_format: :cobra

  # No zap stanza required
end
