# This file was generated by GoReleaser. DO NOT EDIT.
cask "kpg" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "bb14d0ccdb3da1b2b34cafe5c025f9e8d7d8cdfe7abded3f7f45a587e2829b43"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ddbbb45c3824847d3a294b23b56a98e41dd5c8197b91bae187f3d1fe8a1131db"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5a70605cce2ae664c581cdf512ae239bace20b1562db1af8533c0b31dda32c88"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f69e032c4b8c843bc2b3b058febdf1168b8c5227311b97a4a0abcce091d5a074"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kpg"
  desc "Command-first CLI for connecting to Kubernetes-hosted Postgres databases"
  homepage "https://github.com/pscheid92/kpg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kpg"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kpg"]
    end
  end

  # No zap stanza required
end
