# This file was generated by GoReleaser. DO NOT EDIT.
cask "kpg" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kpg"]
    end
  end

  version "0.3.3"

  on_macos do
    on_arm do
      sha256 "7137f694876c9cec2a5ff778f2db6800ea125002ccc7a35132a912718ae6c33b"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a158576ccec14926966c5c8f70ebb1652e4d9aeace44acef659b27de6fb3cc30"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "928f65c9617867df3bb97781594a23f2fbb2f30106ca98907f05c6254b3ec496"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7f5973050e63eda814c1914d00448736d2f9c9a91e4092a81becfadc52fe5ffb"
      url "https://github.com/pscheid92/kpg/releases/download/v#{version}/kpg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kpg"
  desc "Command-first CLI for connecting to Kubernetes-hosted Postgres databases"
  homepage "https://github.com/pscheid92/kpg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kpg"

  generate_completions_from_executable "kpg",
    shell_parameter_format: :cobra

  # No zap stanza required
end
